#version 450
#extension GL_ARB_sparse_texture2 : enable
layout(set = 0, binding = 0) uniform sampler2D s_clamp_max;
layout(set = 0, binding = 1) uniform sampler2D s_nearmip_max;
layout(set = 0, binding = 2) uniform sampler2D s_nearmip_min;
layout(set = 0, binding = 3) uniform sampler2D s_lin_max;
layout(set = 0, binding = 4) uniform sampler2D s_lin_avg;
layout(set = 0, binding = 5) buffer Out { float v[16]; } o;
layout(local_size_x = 1) in;
void main()
{
    o.v[0] = textureLod(s_clamp_max, vec2(0.5), 1.0).r;
    o.v[1] = textureLod(s_nearmip_max, vec2(0.3), 0.5).r;
    o.v[2] = textureLod(s_nearmip_min, vec2(0.3), 0.5).r;
    vec4 t;
    int code = sparseTextureLodARB(s_lin_max, vec2(0.5), 0.0, t);
    o.v[3] = t.r;
    o.v[4] = sparseTexelsResidentARB(code) ? 1.0 : 0.0;
    o.v[5] = textureLod(s_lin_max, vec2(0.5), 0.0).r;
    o.v[6] = textureLod(s_lin_max, vec2(0.5), 0.5).r;
    o.v[7] = textureLod(s_lin_avg, vec2(0.5), 0.0).r;
}
